# Define nossa imagem base
FROM jenkins/jenkins

# Define nosso usuario dentro do container
USER root

# Executa comandos para instalar o python
RUN apt-get update
RUN apt install -y python3-pip
RUN apt install -y python3.11-venv

USER jenkins